# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2", "0002_application_email_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="provide_immutable_email",
            field=models.BooleanField(
                default=False,
                help_text="Always provide the same primary email to the application, instead of selecting the primary email user's list of emails",
                verbose_name="provide immutable primary email to the application",
            ),
        ),
    ]
