# Generated by Django 2.0.7 on 2018-07-26 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_application_allow_access_by_email_suffix_squashed_0005_auto_20180205_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='peers',
            field=models.ManyToManyField(blank=True, related_name='_application_peers_+', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
