# Generated by Django 3.1.5 on 2021-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0011_application_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='redirect_uris',
            field=models.TextField(blank=True, help_text='Allowed URIs list, space separated'),
        ),
    ]
