version: '3'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
  staffsso-data:
    driver: local

services:
  db:
    image: "postgres:10"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=staff-sso
    volumes:
     - staffsso-data:/var/lib/postgresql/data
    ports:
     - 5432:5432
  idp:
    build: ./extras/saml-idp-test/
    ports:
     - 8080:8080
     - 443:443
    environment:
     - SIMPLESAMLPHP_SP_ENTITY_ID=https://sso.staff.service.trade.gov.uk/sp
     - SIMPLESAMLPHP_SECRET_SALT=secret-salt

  web:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PORT=8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - idp
    command: python3 /app/manage.py runserver 0.0.0.0:8000
