# Generated by Django 2.0.8 on 2019-01-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samlidp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samlapplication",
            name="ip_restriction",
        ),
        migrations.AddField(
            model_name="samlapplication",
            name="allowed_ips",
            field=models.CharField(
                blank=True,
                help_text="A comma separated list of allowed ips. Leave blank to disable ip restriction.",
                max_length=255,
                null=True,
                verbose_name="allowed ips",
            ),
        ),
    ]
