# Generated by Django 3.1.5 on 2021-03-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samlidp', '0004_auto_20210305_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SamlApplication',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='real_entity_id',
            field=models.CharField(blank=True, help_text='Takes precendence over the entity_id field and allows for the entity_id field to be an alias', max_length=255, null=True),
        ),
    ]
