# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_emailaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name_plural': 'email addresses'},
        ),
    ]
