# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-25 14:56
from __future__ import unicode_literals

from django.db import migrations


def add_email_to_emailaddress_model(apps, schema_editor):
    User = apps.get_model("user", "User")
    for row in User.objects.all():
        if not row.emails.filter(email=row.email).exists():
            row.emails.create(email=row.email)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_auto_20171124_1626"),
    ]

    operations = [
        migrations.RunPython(
            add_email_to_emailaddress_model, reverse_code=migrations.RunPython.noop
        ),
    ]
