# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20171125_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='A unique account reference'),
        ),
    ]
