# Generated by Django 2.0.8 on 2018-11-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samlidp', '0001_initial'),
        ('user', '0012_auto_20181127_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='saml2_applications',
            field=models.ManyToManyField(related_name='access_profiles', to='samlidp.SamlApplication'),
        ),
    ]
