# Generated by Django 2.0.8 on 2019-01-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_accessprofile_slug'),
        ('user', '0012_auto_20181121_1531'),
    ]

    operations = [
    ]
