# Generated by Django 2.0.8 on 2019-02-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_merge_20190121_1321"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
