# Generated by Django 2.1.7 on 2019-06-04 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_auto_20190604_1437"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_settings",
        ),
        migrations.AddField(
            model_name="user",
            name="user_settings",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
    ]
