# Generated by Django 2.1.7 on 2019-06-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20190604_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_settings',
        ),
    ]
