# Generated by Django 2.2.4 on 2019-12-12 14:27

from django.db import migrations

from sso.user.models import build_email_user_id


def gen_email_unique_id(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        user.email_user_id = build_email_user_id(user.email, user.user_id)
        user.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('user', '0026_user_email_id'),
    ]

    operations = [
        migrations.RunPython(gen_email_unique_id),
    ]
