# Generated by Django 2.2.4 on 2019-12-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20191212_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(help_text='An user id an email compatible format', max_length=254, unique=True),
        ),
    ]
