# Generated by Django 2.2.9 on 2020-02-12 10:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samlidp", "0002_samlapplication_slug"),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("user", "0028_auto_20191216_1453"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_permission_format",
                                message="Permission must only contain letters, numbers and ._-",
                                regex="^[a-zA-Z0-9\\.\\-\\_]*$",
                            )
                        ],
                    ),
                ),
                (
                    "oauth2_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="samlidp.SamlApplication",
                    ),
                ),
                (
                    "saml2_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                    ),
                ),
            ],
        ),
    ]
