# Generated by Django 2.2.13 on 2020-07-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "samlidp",
            "0003_samlapplication_allow_access_by_email_suffix_squashed_0004_auto_20200420_1246",
        ),
        ("user", "0032_user_last_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_emails",
                        to="user.EmailAddress",
                    ),
                ),
                (
                    "saml_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="samlidp.SamlApplication"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_emails",
                        to="user.User",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "saml_application", "email")},
            },
        ),
    ]
