# Generated by Django 2.2.13 on 2020-07-13 14:03

from django.db import migrations


def fill_empty_contact_email_fields(apps, schema_editor):
    User = apps.get_model('user', 'User')
    for user in User.objects.all():
        if not user.contact_email:
            user.contact_email = user.email
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_serviceemailaddress'),
    ]

    operations = [
        migrations.RunPython(fill_empty_contact_email_fields),
    ]
