# Generated by Django 2.2.13 on 2020-09-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_user_is_active'),
        ('user', '0034_remove_user_use_new_journey'),
    ]

    operations = [
    ]
