# Generated by Django 2.2.13 on 2020-07-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_ensure_contact_email_field_is_not_empty_20200713_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
