# Generated by Django 2.2.13 on 2021-01-11 11:42

from django.db import migrations
from django.contrib.admin.models import CHANGE, LogEntry
from django.contrib.contenttypes.models import ContentType


def update_disabled_users(apps, schema_editor):
    ACTION_TEXT = '[{"changed": {"fields": ["is_active"]}}]'

    User = apps.get_model('user', 'User')

    user_type = ContentType.objects.get_for_model(User())

    for user in User.objects.filter(is_active=False):
        if not user.disabled_on:
            log_entry = LogEntry.objects.filter(
                object_id=str(user.id),
                content_type=user_type,
                change_message=ACTION_TEXT,
                action_flag=CHANGE).order_by('-id')

            if log_entry:
                user.disabled_on = log_entry[0].action_time
                user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_user_disabled_on'),
    ]

    operations = [
        migrations.RunPython(update_disabled_users),
    ]
