# Generated by Django 3.1.5 on 2021-03-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.SAML_IDP_SERVICE_PROVIDER_MODEL),
        ('user', '0037_update_became_inactive_on_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessprofile',
            name='saml2_applications',
            field=models.ManyToManyField(blank=True, related_name='access_profiles', to=settings.SAML_IDP_SERVICE_PROVIDER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationpermission',
            name='saml2_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_permissions', to=settings.SAML_IDP_SERVICE_PROVIDER_MODEL),
        ),
    ]
