# Generated by Django 3.1.5 on 2021-03-05 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.SAML_IDP_SERVICE_PROVIDER_MODEL),
        ('user', '0038_auto_20210305_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceemailaddress',
            name='saml_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.SAML_IDP_SERVICE_PROVIDER_MODEL),
        ),
    ]
