# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models

import sso.emailauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("emailauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtoken",
            name="token",
            field=models.CharField(
                default=sso.emailauth.models.generate_token, max_length=128, unique=True
            ),
        ),
    ]
