# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailauth", "0002_auto_20171113_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtoken",
            name="first_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailtoken",
            name="last_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
